export const songs=[
{
 url:'/faded.mp3',
 background:'/faded.jpg',
 title:'Faded',
 artist:'Alan Walker',
 duration:'3:32',
},
{
url:'/lockedaway.mp3',
background:'/lockedaway.jpg',
title:'Locked Away',
artist:'R. City',
duration:'4:32',
   },
   {
    url:'/diamonds.mp3',
    background:'/diamonds.jpg',
    title:'Diamonds',
    artist:'Rihanna',
    duration:'4:17',
   },
   {
      url:'/faded.mp3',
      background:'/faded.jpg',
      title:'Faded',
      artist:'Alan Walker',
      duration:'3:32',
     },
     {
      url:'/faded.mp3',
      background:'/faded.jpg',
      title:'Fiiiiiaded',
      artist:'Alan Walker',
      duration:'3:32',
     },
     {
      url:'/faded.mp3',
      background:'/faded.jpg',
      title:'Faded',
      artist:'Alan Walker',
      duration:'3:32',
     },
     {
      url:'/faded.mp3',
      background:'/faded.jpg',
      title:'Faded',
      artist:'Alan Walker',
      duration:'3:32',
     },
     {
      url:'/faded.mp3',
      background:'/faded.jpg',
      title:'Faded',
      artist:'Alan Walker',
      duration:'3:32',
     },
     {
      url:'/faded.mp3',
      background:'/faded.jpg',
      title:'Faded',
      artist:'Alan Walker',
      duration:'3:32',
     },
     {
      url:'/faded.mp3',
      background:'/faded.jpg',
      title:'Faded',
      artist:'Alan Walker',
      duration:'3:32',
     },
     {
      url:'/faded.mp3',
      background:'/faded.jpg',
      title:'Faded',
      artist:'Alan Walker',
      duration:'3:32',
     },
     {
      url:'/faded.mp3',
      background:'/faded.jpg',
      title:'Faded',
      artist:'Alan Walker',
      duration:'3:32',
     },
     {
      url:'/faded.mp3',
      background:'/faded.jpg',
      title:'Faded',
      artist:'Alan Walker',
      duration:'3:32',
     },
     {
      url:'/faded.mp3',
      background:'/faded.jpg',
      title:'Faded',
      artist:'Alan Walker',
      duration:'3:32',
     },
     {
      url:'/faded.mp3',
      background:'/faded.jpg',
      title:'Faded',
      artist:'Alan Walker',
      duration:'3:32',
     },
     {
      url:'/faded.mp3',
      background:'/faded.jpg',
      title:'Fadedghjhjhj',
      artist:'Alan Walker',
      duration:'3:32',
     }
]
